name: splugin
main: com.erdem.splugin.main
version: 1.0
api-version: 1.13
commands:
   weapon:
      description: gives sword or axe.
      usage: /<command>
   givetracker:
      description: gives compass
      usage: /<command>
      permissions: minecraft.commands.give
   track:
      description: tracks a player
      usage: /<command>